# Generated by Django 4.2.4 on 2023-10-29 09:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_quiz_lesson_quizresult_lesson_question_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_lesson',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
