# Generated by Django 4.2.4 on 2023-10-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_question_lesson_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_lesson',
            name='text',
            field=models.TextField(),
        ),
    ]
